### ISSUE TITLE
Create v1.0.0 tag

### ISSUE THREAD

**Issue by ghost** [2m/fish-jabba#8]
Let's tag what's already in the wild.  I opened a [PR on omf/packages-main](https://github.com/oh-my-fish/packages-main/pull/124) to add fish-jabba to the omf repository.

I think a tagging system is always a good idea, no matter how small the project is. I'm going to take a look at the project and see if I can improve it anywhere.

Thanks for contributing this plugin!

**Comment by 2m** [comment]
Great! I enabled release drafter bot to easily track changes in release drafts and created the first release: https://github.com/2m/fish-jabba/releases/tag/1.0.0
